name: Output Metadata
on: issues
jobs:
  Issues-Occured:
    runs-on: ubuntu-latest
    steps:
      - name: Issue is Occured
        run: echo "${{toJSON(github.event_name)}}"
      - name: Present Working Dirctory
        run: echo "${pwd}}"