name: test deploy workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: INstall Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: echo "Linting the Project...."
      - name: Final Stage of Lint
        run: echo "Linting the Project...."
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Testing
        run: echo "Testing the Project...."
      - name: Final Stage of Testing
        run: echo "Testing Done in Project...."
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Deploying
        run: echo "Deploying the Project...."
      - name: Final Stage of Deploying
        run: echo "Deploying Done ...."

