name: test deploy workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: INstall Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: echo "Linting the Project...."
      - name: Final Stage of Lint
        run: echo "Linting the Project...."

